### ISSUE TITLE
after upgrade "non-existent" civi_flexmailer_required tokens

### ISSUE THREAD

**Issue by Stoob** [civicrm/org.civicrm.flexmailer#24]
Several times on several different installs since the 5.x series, after an upgrade, the following message appears where accessing screens in CiviCRM, both CiviMail and non-CiviMail related.   The solution is simply to clear CiviCRM's cache, or civicrm/menu/rebuild.  However I'm wondering why the cache clear that occurs during or after the upgrade itself is unsufficient and the cache must be cleared again

> Sorry, due to an error, we are unable to fulfill your request...
> You have requested a non-existent service
> "civi_flexmailer_required_tokens".

**Comment by totten** [comment]
The issue is a good point. The same general phenomenon comes in up other cases (i.e. it's not particular to FlexMailer). There is an obscure option (`CIVICRM_CONTAINER_CACHE=auto`) which reduces the frequency of this error, and we changed the default in Civi v5.4+. There's more explanation in the PR:

https://github.com/civicrm/civicrm-core/pull/12426

I haven't specifically re-tested Flexmailer upgrade-paths for this error; however, 12426 should make it a lot better, and I haven't heard new reports of this error since.

If the problem still happens after setting `CIVICRM_CONTAINER_CACHE=auto`, then please feel free to reopen as a core issue (with a link to this and 12426). I'd rather fix the general container behavior in core than put work-arounds into this particular extension.
